In [1]:
import pandas as pd
import numpy as np
import statsmodels.stats as sms
import seaborn as sns
import matplotlib.pyplot as plt
import time
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
sns.set_style('darkgrid')
%load_ext autoreload
%autoreload 2

In [4]:
x = pd.read_pickle('mdf_input_fight_stats.pkl')
y = pd.read_pickle('mdf_targets_fight_stats.pkl')

In [5]:
len(x)

10292

In [6]:
len(y)

10292

In [7]:
y.head()

,TIME,TIMEmod,avg_BODY_att,avg_BODY_landed,avg_CLINCH_att,avg_CLINCH_landed,avg_DISTANCE_att,avg_DISTANCE_landed,avg_GROUND_att,avg_GROUND_landed,...,avg_REV,avg_SIG_STR_att,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed
0,00:15:00,900,14.000000,12.0,6.000,3.000000,26.000000,9.000,8.000000,6.000000,...,1.0,40.0,18.0,0.450000,1.000000,0.000,0.000000,0.000000,137.000000,109.000
1,00:15:00,900,14.333333,11.5,23.000,13.833333,69.166667,21.500,4.333333,3.166667,...,0.0,96.5,38.5,0.381667,0.166667,2.500,0.833333,0.316667,130.833333,70.000
2,00:15:00,900,12.500000,11.0,28.000,15.500000,48.000000,16.000,0.500000,0.500000,...,0.0,76.5,32.0,0.405000,0.500000,3.500,1.000000,0.250000,101.000000,55.000
3,00:15:00,900,13.500000,10.5,19.625,12.375000,68.125000,20.875,3.750000,2.750000,...,0.0,91.5,36.0,0.368750,0.125000,2.875,1.000000,0.283750,127.250000,69.375
4,00:15:00,900,13.250000,11.0,21.250,13.000000,71.500000,26.250,3.250000,2.250000,...,0.0,96.0,41.5,0.422500,0.250000,2.000,0.750000,0.375000,118.000000,61.750

In [8]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10292 entries, 0 to 5145
Data columns (total 26 columns):
TIME                    10292 non-null timedelta64[ns]
TIMEmod                 10292 non-null int64
avg_BODY_att            8375 non-null float64
avg_BODY_landed         8375 non-null float64
avg_CLINCH_att          8375 non-null float64
avg_CLINCH_landed       8375 non-null float64
avg_DISTANCE_att        8375 non-null float64
avg_DISTANCE_landed     8375 non-null float64
avg_GROUND_att          8375 non-null float64
avg_GROUND_landed       8375 non-null float64
avg_HEAD_att            8375 non-null float64
avg_HEAD_landed         8375 non-null float64
avg_KD                  8375 non-null float64
avg_LEG_att             8375 non-null float64
avg_LEG_landed          8375 non-null float64
avg_PASS                8375 non-null float64
avg_REV                 8375 non-null float64
avg_SIG_STR_att         8375 non-null float64
avg_SIG_STR_landed      8375 non-null float64
avg_SIG_STR_pct         8375 non-null float64
avg_SUB_ATT             8375 non-null float64
avg_TD_att              8375 non-null float64
avg_TD_landed           8375 non-null float64
avg_TD_pct              8375 non-null float64
avg_TOTAL_STR_att       8375 non-null float64
avg_TOTAL_STR_landed    8375 non-null float64
dtypes: float64(24), int64(1), timedelta64[ns](1)
memory usage: 2.1 MB

In [9]:
y.loc[y['avg_BODY_att'].isna()]

,TIME,TIMEmod,avg_BODY_att,avg_BODY_landed,avg_CLINCH_att,avg_CLINCH_landed,avg_DISTANCE_att,avg_DISTANCE_landed,avg_GROUND_att,avg_GROUND_landed,...,avg_REV,avg_SIG_STR_att,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed
12,00:01:40,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,00:05:42,342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,00:07:49,469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,00:15:00,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,00:04:53,293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5118,00:14:07,847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5130,00:14:30,870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5136,00:00:43,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5140,00:15:00,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5141,00:15:00,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10292 entries, 0 to 5145
Data columns (total 40 columns):
newindex                      10292 non-null object
Referee                       10246 non-null object
date                          10292 non-null datetime64[ns]
location                      10292 non-null object
title_bout                    10292 non-null bool
weight_class                  10292 non-null object
no_of_rounds                  10292 non-null int64
last_round                    10292 non-null int64
last_round_time               10292 non-null object
Format                        10292 non-null object
Fight_type                    10292 non-null object
Draw                          10292 non-null uint8
Red                           10292 non-null uint8
fighter                       10292 non-null object
current_lose_streak           10292 non-null float64
current_win_streak            10292 non-null float64
draw                          10292 non-null float64
longest_win_streak            10292 non-null float64
losses                        10292 non-null float64
total_rounds_fought           10292 non-null float64
total_time_fought(seconds)    8375 non-null float64
total_title_bouts             10292 non-null float64
win_by_Decision_Majority      10292 non-null float64
win_by_Decision_Split         10292 non-null float64
win_by_Decision_Unanimous     10292 non-null float64
win_by_KO/TKO                 10292 non-null float64
win_by_Submission             10292 non-null float64
win_by_TKO_Doctor_Stoppage    10292 non-null float64
wins                          10292 non-null float64
Stance                        10292 non-null object
Height_cms                    10292 non-null float64
Reach_cms                     10292 non-null float64
Weight_lbs                    10283 non-null float64
age                           10054 non-null float64
Weight_cms                    9 non-null float64
stance__Open Stance           10292 non-null uint8
stance__Orthodox              10292 non-null uint8
stance__Sideways              10292 non-null uint8
stance__Southpaw              10292 non-null uint8
stance__Switch                10292 non-null uint8
dtypes: bool(1), datetime64[ns](1), float64(20), int64(2), object(9), uint8(7)
memory usage: 2.7+ MB

In [13]:
x.drop(columns=['Weight_cms'],inplace=True)

In [24]:
x.loc[x.Weight_lbs.isna(), 'Weight_lbs'] = x.Weight_lbs.mean()

In [26]:
# given the high nr of Naans, going to briefly join the two tables, drop nans, split again
test_df = pd.concat([x,y], axis=1)

In [27]:
len(test_df)

10292

In [28]:
test_df.tail()

,newindex,Referee,date,location,title_bout,weight_class,no_of_rounds,last_round,last_round_time,Format,...,avg_REV,avg_SIG_STR_att,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed
5141,Zhang LipengBrendan O'Reilly2014-08-23,John Sharp,2014-08-23,"Macau, China",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5142,Zhang LipengChris Wade2015-01-18,Kevin MacDonald,2015-01-18,"Boston, Massachusetts, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,0.0,1.0,0.0,0.000,1.0,1.0,1.0,1.000,6.00,5.0
5143,Zhang LipengKajan Johnson2015-05-16,Greg Kleynjans,2015-05-16,"Manila, Philippines",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,1.0,91.0,29.0,0.310,0.0,9.0,4.0,0.440,91.00,29.0
5144,Zubaira TukhugovErnest Chavez2014-10-04,Bobby Rehman,2014-10-04,"Stockholm, Sweden",False,Featherweight,3,1,4:21,3 Rnd (5-5-5),...,0.0,100.5,41.0,0.415,0.0,3.0,1.0,0.500,139.50,77.5
5145,Zubaira TukhugovPhillipe Nover2015-12-10,Mark Smith,2015-12-10,"Las Vegas, Nevada, USA",False,Featherweight,3,3,5:00,3 Rnd (5-5-5),...,0.5,34.5,13.5,0.380,1.0,3.5,1.5,0.125,70.75,47.0

In [29]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10292 entries, 0 to 5145
Data columns (total 65 columns):
newindex                      10292 non-null object
Referee                       10246 non-null object
date                          10292 non-null datetime64[ns]
location                      10292 non-null object
title_bout                    10292 non-null bool
weight_class                  10292 non-null object
no_of_rounds                  10292 non-null int64
last_round                    10292 non-null int64
last_round_time               10292 non-null object
Format                        10292 non-null object
Fight_type                    10292 non-null object
Draw                          10292 non-null uint8
Red                           10292 non-null uint8
fighter                       10292 non-null object
current_lose_streak           10292 non-null float64
current_win_streak            10292 non-null float64
draw                          10292 non-null float64
longest_win_streak            10292 non-null float64
losses                        10292 non-null float64
total_rounds_fought           10292 non-null float64
total_time_fought(seconds)    8375 non-null float64
total_title_bouts             10292 non-null float64
win_by_Decision_Majority      10292 non-null float64
win_by_Decision_Split         10292 non-null float64
win_by_Decision_Unanimous     10292 non-null float64
win_by_KO/TKO                 10292 non-null float64
win_by_Submission             10292 non-null float64
win_by_TKO_Doctor_Stoppage    10292 non-null float64
wins                          10292 non-null float64
Stance                        10292 non-null object
Height_cms                    10292 non-null float64
Reach_cms                     10292 non-null float64
Weight_lbs                    10292 non-null float64
age                           10054 non-null float64
stance__Open Stance           10292 non-null uint8
stance__Orthodox              10292 non-null uint8
stance__Sideways              10292 non-null uint8
stance__Southpaw              10292 non-null uint8
stance__Switch                10292 non-null uint8
TIME                          10292 non-null timedelta64[ns]
TIMEmod                       10292 non-null int64
avg_BODY_att                  8375 non-null float64
avg_BODY_landed               8375 non-null float64
avg_CLINCH_att                8375 non-null float64
avg_CLINCH_landed             8375 non-null float64
avg_DISTANCE_att              8375 non-null float64
avg_DISTANCE_landed           8375 non-null float64
avg_GROUND_att                8375 non-null float64
avg_GROUND_landed             8375 non-null float64
avg_HEAD_att                  8375 non-null float64
avg_HEAD_landed               8375 non-null float64
avg_KD                        8375 non-null float64
avg_LEG_att                   8375 non-null float64
avg_LEG_landed                8375 non-null float64
avg_PASS                      8375 non-null float64
avg_REV                       8375 non-null float64
avg_SIG_STR_att               8375 non-null float64
avg_SIG_STR_landed            8375 non-null float64
avg_SIG_STR_pct               8375 non-null float64
avg_SUB_ATT                   8375 non-null float64
avg_TD_att                    8375 non-null float64
avg_TD_landed                 8375 non-null float64
avg_TD_pct                    8375 non-null float64
avg_TOTAL_STR_att             8375 non-null float64
avg_TOTAL_STR_landed          8375 non-null float64
dtypes: bool(1), datetime64[ns](1), float64(43), int64(3), object(9), timedelta64[ns](1), uint8(7)
memory usage: 4.9+ MB

In [30]:
df_redux = test_df.loc[~test_df.avg_BODY_att.isna()]

In [32]:
df_redux.tail()

,newindex,Referee,date,location,title_bout,weight_class,no_of_rounds,last_round,last_round_time,Format,...,avg_REV,avg_SIG_STR_att,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed
5139,Zak CummingsTrevin Giles2019-05-18,Todd Ronald Anderson,2019-05-18,"Rochester, New York, USA",False,Middleweight,3,3,4:01,3 Rnd (5-5-5),...,0.0,83.0,55.5,0.690,0.0,2.5,2.5,0.500,93.00,65.5
5142,Zhang LipengChris Wade2015-01-18,Kevin MacDonald,2015-01-18,"Boston, Massachusetts, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,0.0,1.0,0.0,0.000,1.0,1.0,1.0,1.000,6.00,5.0
5143,Zhang LipengKajan Johnson2015-05-16,Greg Kleynjans,2015-05-16,"Manila, Philippines",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,1.0,91.0,29.0,0.310,0.0,9.0,4.0,0.440,91.00,29.0
5144,Zubaira TukhugovErnest Chavez2014-10-04,Bobby Rehman,2014-10-04,"Stockholm, Sweden",False,Featherweight,3,1,4:21,3 Rnd (5-5-5),...,0.0,100.5,41.0,0.415,0.0,3.0,1.0,0.500,139.50,77.5
5145,Zubaira TukhugovPhillipe Nover2015-12-10,Mark Smith,2015-12-10,"Las Vegas, Nevada, USA",False,Featherweight,3,3,5:00,3 Rnd (5-5-5),...,0.5,34.5,13.5,0.380,1.0,3.5,1.5,0.125,70.75,47.0

In [33]:
for i, c in enumerate(df_redux.columns):
    print(i,c)

0 newindex
1 Referee
2 date
3 location
4 title_bout
5 weight_class
6 no_of_rounds
7 last_round
8 last_round_time
9 Format
10 Fight_type
11 Draw
12 Red
13 fighter
14 current_lose_streak
15 current_win_streak
16 draw
17 longest_win_streak
18 losses
19 total_rounds_fought
20 total_time_fought(seconds)
21 total_title_bouts
22 win_by_Decision_Majority
23 win_by_Decision_Split
24 win_by_Decision_Unanimous
25 win_by_KO/TKO
26 win_by_Submission
27 win_by_TKO_Doctor_Stoppage
28 wins
29 Stance
30 Height_cms
31 Reach_cms
32 Weight_lbs
33 age
34 stance__Open Stance
35 stance__Orthodox
36 stance__Sideways
37 stance__Southpaw
38 stance__Switch
39 TIME
40 TIMEmod
41 avg_BODY_att
42 avg_BODY_landed
43 avg_CLINCH_att
44 avg_CLINCH_landed
45 avg_DISTANCE_att
46 avg_DISTANCE_landed
47 avg_GROUND_att
48 avg_GROUND_landed
49 avg_HEAD_att
50 avg_HEAD_landed
51 avg_KD
52 avg_LEG_att
53 avg_LEG_landed
54 avg_PASS
55 avg_REV
56 avg_SIG_STR_att
57 avg_SIG_STR_landed
58 avg_SIG_STR_pct
59 avg_SUB_ATT
60 avg_TD_att
61 avg_TD_landed
62 avg_TD_pct
63 avg_TOTAL_STR_att
64 avg_TOTAL_STR_landed

In [79]:
x_redux = df_redux[df_redux.columns[:39]]
y_redux = df_redux[df_redux.columns[39:]]

In [80]:
x_redux.drop(columns=['Referee', 'date','location', 'title_bout', 'weight_class','Format', 'Fight_type','Draw','Red','fighter'], inplace=True)

/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/pandas/core/frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [81]:
x_redux.head()

,newindex,no_of_rounds,last_round,last_round_time,current_lose_streak,current_win_streak,draw,longest_win_streak,losses,total_rounds_fought,...,Stance,Height_cms,Reach_cms,Weight_lbs,age,stance__Open Stance,stance__Orthodox,stance__Sideways,stance__Southpaw,stance__Switch
0,Aaron PhillipsMatt Hobar2014-08-23,3,3,5:00,1.0,0.0,0.0,0.0,1.0,3.0,...,Southpaw,175.26,177.80,135.0,25.0,0,0,0,1,0
1,Aaron RileyJoe Brammer2010-05-29,3,3,5:00,1.0,0.0,0.0,1.0,4.0,13.0,...,Southpaw,172.72,175.26,155.0,29.0,0,0,0,1,0
2,Aaron RileyJorge Gurgel2008-11-15,3,3,5:00,2.0,0.0,0.0,0.0,2.0,4.0,...,Southpaw,172.72,175.26,155.0,27.0,0,0,0,1,0
3,Aaron RileyJustin Salas2013-07-27,3,3,5:00,1.0,0.0,0.0,1.0,5.0,17.0,...,Southpaw,172.72,175.26,155.0,32.0,0,0,0,1,0
4,Aaron RileyShane Nelson2009-08-08,3,3,5:00,1.0,0.0,0.0,1.0,3.0,8.0,...,Southpaw,172.72,175.26,155.0,28.0,0,0,0,1,0

In [82]:
x_redux.set_index('newindex', drop=True, inplace=True)

In [83]:
x_redux.head()

,no_of_rounds,last_round,last_round_time,current_lose_streak,current_win_streak,draw,longest_win_streak,losses,total_rounds_fought,total_time_fought(seconds),...,Stance,Height_cms,Reach_cms,Weight_lbs,age,stance__Open Stance,stance__Orthodox,stance__Sideways,stance__Southpaw,stance__Switch
newindex,,,,,,,,,,,,,,,,,,,,,
Aaron PhillipsMatt Hobar2014-08-23,3,3,5:00,1.0,0.0,0.0,0.0,1.0,3.0,900.000000,...,Southpaw,175.26,177.80,135.0,25.0,0,0,0,1,0
Aaron RileyJoe Brammer2010-05-29,3,3,5:00,1.0,0.0,0.0,1.0,4.0,13.0,603.666667,...,Southpaw,172.72,175.26,155.0,29.0,0,0,0,1,0
Aaron RileyJorge Gurgel2008-11-15,3,3,5:00,2.0,0.0,0.0,0.0,2.0,4.0,600.000000,...,Southpaw,172.72,175.26,155.0,27.0,0,0,0,1,0
Aaron RileyJustin Salas2013-07-27,3,3,5:00,1.0,0.0,0.0,1.0,5.0,17.0,602.750000,...,Southpaw,172.72,175.26,155.0,32.0,0,0,0,1,0
Aaron RileyShane Nelson2009-08-08,3,3,5:00,1.0,0.0,0.0,1.0,3.0,8.0,536.000000,...,Southpaw,172.72,175.26,155.0,28.0,0,0,0,1,0

In [84]:
y_redux.head()

,TIME,TIMEmod,avg_BODY_att,avg_BODY_landed,avg_CLINCH_att,avg_CLINCH_landed,avg_DISTANCE_att,avg_DISTANCE_landed,avg_GROUND_att,avg_GROUND_landed,...,avg_REV,avg_SIG_STR_att,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed
0,00:15:00,900,14.000000,12.0,6.000,3.000000,26.000000,9.000,8.000000,6.000000,...,1.0,40.0,18.0,0.450000,1.000000,0.000,0.000000,0.000000,137.000000,109.000
1,00:15:00,900,14.333333,11.5,23.000,13.833333,69.166667,21.500,4.333333,3.166667,...,0.0,96.5,38.5,0.381667,0.166667,2.500,0.833333,0.316667,130.833333,70.000
2,00:15:00,900,12.500000,11.0,28.000,15.500000,48.000000,16.000,0.500000,0.500000,...,0.0,76.5,32.0,0.405000,0.500000,3.500,1.000000,0.250000,101.000000,55.000
3,00:15:00,900,13.500000,10.5,19.625,12.375000,68.125000,20.875,3.750000,2.750000,...,0.0,91.5,36.0,0.368750,0.125000,2.875,1.000000,0.283750,127.250000,69.375
4,00:15:00,900,13.250000,11.0,21.250,13.000000,71.500000,26.250,3.250000,2.250000,...,0.0,96.0,41.5,0.422500,0.250000,2.000,0.750000,0.375000,118.000000,61.750

In [85]:
y_redux['newindex'] = df_redux['newindex']

/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [86]:
y_redux.head()

,TIME,TIMEmod,avg_BODY_att,avg_BODY_landed,avg_CLINCH_att,avg_CLINCH_landed,avg_DISTANCE_att,avg_DISTANCE_landed,avg_GROUND_att,avg_GROUND_landed,...,avg_SIG_STR_att,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed,newindex
0,00:15:00,900,14.000000,12.0,6.000,3.000000,26.000000,9.000,8.000000,6.000000,...,40.0,18.0,0.450000,1.000000,0.000,0.000000,0.000000,137.000000,109.000,Aaron PhillipsMatt Hobar2014-08-23
1,00:15:00,900,14.333333,11.5,23.000,13.833333,69.166667,21.500,4.333333,3.166667,...,96.5,38.5,0.381667,0.166667,2.500,0.833333,0.316667,130.833333,70.000,Aaron RileyJoe Brammer2010-05-29
2,00:15:00,900,12.500000,11.0,28.000,15.500000,48.000000,16.000,0.500000,0.500000,...,76.5,32.0,0.405000,0.500000,3.500,1.000000,0.250000,101.000000,55.000,Aaron RileyJorge Gurgel2008-11-15
3,00:15:00,900,13.500000,10.5,19.625,12.375000,68.125000,20.875,3.750000,2.750000,...,91.5,36.0,0.368750,0.125000,2.875,1.000000,0.283750,127.250000,69.375,Aaron RileyJustin Salas2013-07-27
4,00:15:00,900,13.250000,11.0,21.250,13.000000,71.500000,26.250,3.250000,2.250000,...,96.0,41.5,0.422500,0.250000,2.000,0.750000,0.375000,118.000000,61.750,Aaron RileyShane Nelson2009-08-08

In [87]:
y_redux['Red_win'] = df_redux['Red']
y_redux['Draw_win'] = df_redux['Draw']
y_redux.head()

/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,TIME,TIMEmod,avg_BODY_att,avg_BODY_landed,avg_CLINCH_att,avg_CLINCH_landed,avg_DISTANCE_att,avg_DISTANCE_landed,avg_GROUND_att,avg_GROUND_landed,...,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed,newindex,Red_win,Draw_win
0,00:15:00,900,14.000000,12.0,6.000,3.000000,26.000000,9.000,8.000000,6.000000,...,0.450000,1.000000,0.000,0.000000,0.000000,137.000000,109.000,Aaron PhillipsMatt Hobar2014-08-23,0,0
1,00:15:00,900,14.333333,11.5,23.000,13.833333,69.166667,21.500,4.333333,3.166667,...,0.381667,0.166667,2.500,0.833333,0.316667,130.833333,70.000,Aaron RileyJoe Brammer2010-05-29,1,0
2,00:15:00,900,12.500000,11.0,28.000,15.500000,48.000000,16.000,0.500000,0.500000,...,0.405000,0.500000,3.500,1.000000,0.250000,101.000000,55.000,Aaron RileyJorge Gurgel2008-11-15,1,0
3,00:15:00,900,13.500000,10.5,19.625,12.375000,68.125000,20.875,3.750000,2.750000,...,0.368750,0.125000,2.875,1.000000,0.283750,127.250000,69.375,Aaron RileyJustin Salas2013-07-27,0,0
4,00:15:00,900,13.250000,11.0,21.250,13.000000,71.500000,26.250,3.250000,2.250000,...,0.422500,0.250000,2.000,0.750000,0.375000,118.000000,61.750,Aaron RileyShane Nelson2009-08-08,1,0

In [88]:
y_redux.set_index('newindex', drop=True, inplace=True)

In [89]:
y_redux

,TIME,TIMEmod,avg_BODY_att,avg_BODY_landed,avg_CLINCH_att,avg_CLINCH_landed,avg_DISTANCE_att,avg_DISTANCE_landed,avg_GROUND_att,avg_GROUND_landed,...,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed,Red_win,Draw_win
newindex,,,,,,,,,,,,,,,,,,,,,
Aaron PhillipsMatt Hobar2014-08-23,00:15:00,900,14.000000,12.00,6.000,3.000000,26.000000,9.000,8.000000,6.000000,...,18.0,0.450000,1.000000,0.000,0.000000,0.000000,137.000000,109.000,0,0
Aaron RileyJoe Brammer2010-05-29,00:15:00,900,14.333333,11.50,23.000,13.833333,69.166667,21.500,4.333333,3.166667,...,38.5,0.381667,0.166667,2.500,0.833333,0.316667,130.833333,70.000,1,0
Aaron RileyJorge Gurgel2008-11-15,00:15:00,900,12.500000,11.00,28.000,15.500000,48.000000,16.000,0.500000,0.500000,...,32.0,0.405000,0.500000,3.500,1.000000,0.250000,101.000000,55.000,1,0
Aaron RileyJustin Salas2013-07-27,00:15:00,900,13.500000,10.50,19.625,12.375000,68.125000,20.875,3.750000,2.750000,...,36.0,0.368750,0.125000,2.875,1.000000,0.283750,127.250000,69.375,0,0
Aaron RileyShane Nelson2009-08-08,00:15:00,900,13.250000,11.00,21.250,13.000000,71.500000,26.250,3.250000,2.250000,...,41.5,0.422500,0.250000,2.000,0.750000,0.375000,118.000000,61.750,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zak CummingsTrevin Giles2019-05-18,00:14:01,841,7.000000,6.00,2.500,2.500000,62.000000,38.000,18.500000,15.000000,...,55.5,0.690000,0.000000,2.500,2.500000,0.500000,93.000000,65.500,1,0
Zhang LipengChris Wade2015-01-18,00:15:00,900,0.000000,0.00,0.000,0.000000,1.000000,0.000,0.000000,0.000000,...,0.0,0.000000,1.000000,1.000,1.000000,1.000000,6.000000,5.000,0,0
Zhang LipengKajan Johnson2015-05-16,00:15:00,900,10.000000,5.00,2.000,2.000000,86.000000,26.000,3.000000,1.000000,...,29.0,0.310000,0.000000,9.000,4.000000,0.440000,91.000000,29.000,0,0
Zubaira TukhugovErnest Chavez2014-10-04,00:04:21,261,14.500000,8.50,8.500,6.000000,91.000000,34.500,1.000000,0.500000,...,41.0,0.415000,0.000000,3.000,1.000000,0.500000,139.500000,77.500,1,0
Zubaira TukhugovPhillipe Nover2015-12-10,00:15:00,900,6.500000,4.25,7.000,5.500000,23.750000,7.000,3.750000,1.000000,...,13.5,0.380000,1.000000,3.500,1.500000,0.125000,70.750000,47.000,1,0

In [90]:
y_redux.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8375 entries, Aaron PhillipsMatt Hobar2014-08-23 to Zubaira TukhugovPhillipe Nover2015-12-10
Data columns (total 28 columns):
TIME                    8375 non-null timedelta64[ns]
TIMEmod                 8375 non-null int64
avg_BODY_att            8375 non-null float64
avg_BODY_landed         8375 non-null float64
avg_CLINCH_att          8375 non-null float64
avg_CLINCH_landed       8375 non-null float64
avg_DISTANCE_att        8375 non-null float64
avg_DISTANCE_landed     8375 non-null float64
avg_GROUND_att          8375 non-null float64
avg_GROUND_landed       8375 non-null float64
avg_HEAD_att            8375 non-null float64
avg_HEAD_landed         8375 non-null float64
avg_KD                  8375 non-null float64
avg_LEG_att             8375 non-null float64
avg_LEG_landed          8375 non-null float64
avg_PASS                8375 non-null float64
avg_REV                 8375 non-null float64
avg_SIG_STR_att         8375 non-null float64
avg_SIG_STR_landed      8375 non-null float64
avg_SIG_STR_pct         8375 non-null float64
avg_SUB_ATT             8375 non-null float64
avg_TD_att              8375 non-null float64
avg_TD_landed           8375 non-null float64
avg_TD_pct              8375 non-null float64
avg_TOTAL_STR_att       8375 non-null float64
avg_TOTAL_STR_landed    8375 non-null float64
Red_win                 8375 non-null uint8
Draw_win                8375 non-null uint8
dtypes: float64(24), int64(1), timedelta64[ns](1), uint8(2)
memory usage: 1.7+ MB

In [91]:
x_redux.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8375 entries, Aaron PhillipsMatt Hobar2014-08-23 to Zubaira TukhugovPhillipe Nover2015-12-10
Data columns (total 28 columns):
no_of_rounds                  8375 non-null int64
last_round                    8375 non-null int64
last_round_time               8375 non-null object
current_lose_streak           8375 non-null float64
current_win_streak            8375 non-null float64
draw                          8375 non-null float64
longest_win_streak            8375 non-null float64
losses                        8375 non-null float64
total_rounds_fought           8375 non-null float64
total_time_fought(seconds)    8375 non-null float64
total_title_bouts             8375 non-null float64
win_by_Decision_Majority      8375 non-null float64
win_by_Decision_Split         8375 non-null float64
win_by_Decision_Unanimous     8375 non-null float64
win_by_KO/TKO                 8375 non-null float64
win_by_Submission             8375 non-null float64
win_by_TKO_Doctor_Stoppage    8375 non-null float64
wins                          8375 non-null float64
Stance                        8375 non-null object
Height_cms                    8375 non-null float64
Reach_cms                     8375 non-null float64
Weight_lbs                    8375 non-null float64
age                           8278 non-null float64
stance__Open Stance           8375 non-null uint8
stance__Orthodox              8375 non-null uint8
stance__Sideways              8375 non-null uint8
stance__Southpaw              8375 non-null uint8
stance__Switch                8375 non-null uint8
dtypes: float64(19), int64(2), object(2), uint8(5)
memory usage: 1.6+ MB

In [92]:
x_redux.age.max()

47.0

In [93]:
x_redux.age.median()

29.0

In [94]:
x_redux.loc[x_redux.age.isna(), 'age'] = x_redux.age.median()

In [95]:
x_redux.drop(columns=['Stance', 'last_round', 'last_round_time'], inplace=True)

In [100]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_redux, y_redux, test_size=.2, random_state=42)


# scaler= StandardScaler()

# x_train_scaled = scaler.fit_transform(x_train)
# x_test_scaled = scaler.transform(x_test)

In [106]:
#  alrighty, time to do some good ol' modellin'
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Lasso
from sklearn.model_selection import cross_val_score, KFold

poly = PolynomialFeatures(3)
x_poly_train = poly.fit_transform(x_train)
x_poly_test = poly.transform(x_test)

In [117]:
y_redux.drop(columns=['TIME'], inplace=True)

/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/pandas/core/frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [137]:
def find_best_target(x_df, y_df, lasso_lambda, n_splits=10, poly_order=2, lasso_tol=0.0001, max_iterations=1000):
    
    scaler= StandardScaler()
    
    for col in y_df.columns:
        x_train, x_test, y_train, y_test = train_test_split(x_df, y_df[col], test_size=.2, random_state=42)
        

        x_train = scaler.fit_transform(x_train)
        x_test = scaler.transform(x_test)
        
        poly = PolynomialFeatures(poly_order)
        x_train = poly.fit_transform(x_train)
        x_test = poly.transform(x_test)
        
        reg_poly = Lasso(alpha=lasso_lambda,tol=lasso_tol,max_iter=max_iterations)
        fit = reg_poly.fit(x_train, y_train)
        score_train = reg_poly.score(x_train, y_train)
        score_test = reg_poly.score(x_test, y_test)
        
        crossval = KFold(n_splits, shuffle=True, random_state=42)
        cvs = cross_val_score(reg_poly, x_train, y_train, scoring='r2', cv=crossval)
        cvs_mean_score = np.mean(cvs)
        
        print(f'''R2 for training data fitting to variable: {col} is {score_train}. \n
              CVS = {cvs_mean_score} . \n
              R2 for testing data fitting to variable: {col} is {score_test} \n.''')
        
        return reg_poly

In [138]:
find_best_target(x_df = x_redux, y_df = y_redux, lasso_lambda=0.4, n_splits=10, lasso_tol=0.01, max_iterations=1000)

R2 for training data fitting to variable: TIMEmod is 0.13133827431013656.

              CVS = 0.06284624092673288 .

              R2 for testing data fitting to variable: TIMEmod is 0.10297279198208831
.

Lasso(alpha=0.4, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.01, warm_start=False)

In [139]:
find_best_target(x_df = x_redux, y_df = y_redux, lasso_lambda=0.4, n_splits=10, lasso_tol=0.01, max_iterations=5000)

R2 for training data fitting to variable: TIMEmod is 0.13133827431013656.

              CVS = 0.06284624092673288 .

              R2 for testing data fitting to variable: TIMEmod is 0.10297279198208831
.

Lasso(alpha=0.4, copy_X=True, fit_intercept=True, max_iter=5000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.01, warm_start=False)

In [140]:
find_best_target(x_df = x_redux, y_df = y_redux, lasso_lambda=0.8, n_splits=10, lasso_tol=0.01, max_iterations=5000)

R2 for training data fitting to variable: TIMEmod is 0.12670133952195672.

              CVS = 0.0690464144035078 .

              R2 for testing data fitting to variable: TIMEmod is 0.10783762187632129
.

Lasso(alpha=0.8, copy_X=True, fit_intercept=True, max_iter=5000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.01, warm_start=False)

In [141]:
find_best_target(x_df = x_redux, y_df = y_redux, lasso_lambda=0.01, n_splits=10, lasso_tol=0.01, max_iterations=1000)

/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 350703234.0795198, tolerance: 8817835.58987463
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 306006782.9787311, tolerance: 7902492.587854064
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 320326673.77649784, tolerance: 7994004.88747761
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 311460960.75935066, tolerance: 7897830.260266996
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 309713495.79960567, tolerance: 7920138.350893864
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 315723797.4344113, tolerance: 7935248.051212273
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 312462572.7535135, tolerance: 7955536.531973469
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 307353662.6726376, tolerance: 7952606.614761195
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 295662443.14201295, tolerance: 7962246.415197349
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 313111114.5547655, tolerance: 7938406.459749583
  positive)

R2 for training data fitting to variable: TIMEmod is 0.136644008527407.

              CVS = 0.046358868067222045 .

              R2 for testing data fitting to variable: TIMEmod is 0.08212418018508805
.

/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 306151165.64302206, tolerance: 7900506.66654063
  positive)

Lasso(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.01, warm_start=False)

In [142]:
find_best_target(x_df = x_redux, y_df = y_redux, lasso_lambda=0.01, n_splits=10, lasso_tol=0.1, max_iterations=1000)

/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 350703234.0795198, tolerance: 88178355.89874631
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 306006782.9787311, tolerance: 79024925.87854064
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 320326673.77649784, tolerance: 79940048.87477611
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 311460960.75935066, tolerance: 78978302.60266995
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 309713495.79960567, tolerance: 79201383.50893866
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 315723797.4344113, tolerance: 79352480.51212274
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 312462572.7535135, tolerance: 79555365.3197347
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 307353662.6726376, tolerance: 79526066.14761196
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 295662443.14201295, tolerance: 79622464.15197349
  positive)
/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 313111114.5547655, tolerance: 79384064.59749584
  positive)

R2 for training data fitting to variable: TIMEmod is 0.136644008527407.

              CVS = 0.046358868067222045 .

              R2 for testing data fitting to variable: TIMEmod is 0.08212418018508805
.

/Users/flatironschool/anaconda3/envs/learn-env/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 306151165.64302206, tolerance: 79005066.6654063
  positive)

Lasso(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.1, warm_start=False)

In [143]:
len(y_redux)

8375

In [144]:
pd.to_pickle(y_redux, 'CLEAN_target_fightstats.pkl')
pd.to_pickle(x_redux, 'CLEAN_input_fightstats.pkl')